<!-- All Javascripts -->
<script src="{{ asset('dist-front/js/jquery-3.6.0.min.js') }}"></script>
<script src="{{ asset('dist-front/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('dist-front/js/jquery-ui.js') }}"></script>
<script src="{{ asset('dist-front/js/jquery.magnific-popup.min.js') }}"></script>
<script src="{{ asset('dist-front/js/owl.carousel.min.js') }}"></script>
<script src="{{ asset('dist-front/js/wow.min.js') }}"></script>
<script src="{{ asset('dist-front/js/select2.full.js') }}"></script>
<script src="{{ asset('dist-front/js/sweetalert2.min.js') }}"></script>
<script src="{{ asset('dist-front/js/iziToast.min.js') }}"></script>
<script src="{{ asset('dist-front/js/jquery.waypoints.min.js') }}"></script>
<script src="{{ asset('dist-front/js/acmeticker.js') }}"></script>